In [8]:
import pandas as pd
import sys
sys.path.insert(1, '/people/imal967/git_repos/ProCaliper')
import procaliper as am
import glob

In [9]:
full_psp_df = pd.read_csv("/people/imal967/git_repos/pheno_analysis/results/merged_interface_pocket_stability.csv")
full_psp_df

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,GENE,PROTEIN,ACC_ID,HU_CHR_LOC,MOD_RSD,SITE_GRP_ID,ORGANISM,...,inside_interface,distance_from_interface,uniqueID,closest_pocket,inside_pocket,distance_from_pocket,foldx_ddg_min,foldx_ddg_max,foldx_ddg_abs_max,foldx_ddg_abs_median
0,0,0,0,YWHAB,14-3-3 beta,P31946,20q13.12,T2-p,15718712,human,...,0,18.400596,0,2,0,22.103256,-0.700058,0.130120,0.700058,0.096524
1,1,1,1,YWHAB,14-3-3 beta,P31946,20q13.12,S6-p,15718709,human,...,1,0.000000,1,10,0,18.407673,-0.688997,0.643053,0.688997,0.278294
2,2,2,2,YWHAB,14-3-3 beta,P31946,20q13.12,Y21-p,3426383,human,...,1,0.000000,2,",2,15",1,0.000000,0.250080,3.602560,3.602560,2.686420
3,3,3,3,YWHAB,14-3-3 beta,P31946,20q13.12,T32-p,23077803,human,...,0,15.828202,3,10,0,12.921682,-2.085020,19.898600,19.898600,3.844370
4,4,4,4,YWHAB,14-3-3 beta,P31946,20q13.12,S39-p,27442700,human,...,0,16.123331,4,",10",1,0.000000,-1.610100,2.446650,2.446650,1.516780
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
436007,436007,435125,435258,PRAP1,PRAP1,Q96NZ9,10q26.3,Y113-ga,27914389,human,...,0,19.475904,435258,1,0,22.441628,-0.310755,0.859067,0.859067,0.516341
436008,436008,435127,435260,PRG2,PRG2,P13727,11q12.1,T23-ga,27914778,human,...,0,25.513050,435260,4,0,26.709694,-0.312937,0.381937,0.381937,0.134005
436009,436009,435128,435261,PRG2,PRG2,P13727,11q12.1,S24-ga,27914781,human,...,0,27.206643,435261,4,0,29.435677,-1.365570,0.171909,1.365570,0.471913
436010,436010,435129,435262,PRG2,PRG2,P13727,11q12.1,T25-ga,27914784,human,...,0,29.210871,435262,4,0,30.474608,-0.118950,0.782394,0.782394,0.100066
436011,436011,435308,435441,SPRING1,SPRING1,Q9H741,12q24.22,T185-ga,27916207,human,...,1,0.000000,435441,",8",1,0.000000,-1.067080,2.291700,2.291700,0.433679

In [10]:
full_psp_df.columns

Index(['Unnamed: 0.2', 'Unnamed: 0.1', 'Unnamed: 0', 'GENE', 'PROTEIN',
       'ACC_ID', 'HU_CHR_LOC', 'MOD_RSD', 'SITE_GRP_ID', 'ORGANISM', 'MW_kD',
       'DOMAIN', 'SITE_+/-7_AA', 'LT_LIT', 'MS_LIT', 'MS_CST', 'CST_CAT#',
       'Ambiguous_Site', 'RES_NUM', 'PKA_ID', 'uniprotID', 'AA', 'res_number',
       'pK', 'state', 'position', 'uniprot_id', 'closest_interface',
       'inside_interface', 'distance_from_interface', 'uniqueID',
       'closest_pocket', 'inside_pocket', 'distance_from_pocket',
       'foldx_ddg_min', 'foldx_ddg_max', 'foldx_ddg_abs_max',
       'foldx_ddg_abs_median'],
      dtype='object')

In [11]:
all_uniprots_list = full_psp_df['ACC_ID'].unique()
all_uniprots_list

array(['P31946', 'P31946-2', 'P62258', ..., 'Q96NZ9', 'P13727', 'Q9H741'],
      dtype=object)

In [12]:
all_uniprots_list[0]

'P31946'

In [13]:
# fetching pdb for each uniprot
protein_object = am.Protein.from_uniprot_id(all_uniprots_list[0])
protein_object

Fetched: 1 / 1

In [14]:
protein_object.data['entry']

'P31946'

In [15]:
glob.glob(f"/rcfs/projects/proteometer/alphafold_swissprot_pdb/*{protein_object.data['entry']}*.pdb")[0]

'/rcfs/projects/proteometer/alphafold_swissprot_pdb/AF-P31946-F1-model_v4.pdb'

In [16]:
protein_object.register_local_pdb("/rcfs/projects/proteometer/alphafold_swissprot_pdb/AF-P31946-F1-model_v4.pdb")

In [17]:
sasa = pd.DataFrame(protein_object.get_sasa())
sasa

,all_sasa_value,atom_sasa_values,residue_number,residue_name
0,237.934137,"[44.837124511298896, 9.66102572831933, 2.41525...",1,MET
1,131.572602,"[3.280765208143822, 3.622884648119749, 0.0, 8....",2,THR
2,74.875928,"[5.467942013573036, 1.2076282160399163, 0.0, 2...",3,MET
3,82.459883,"[1.0935884027146072, 4.830512864159665, 0.0, 2...",4,ASP
4,52.518633,"[2.1871768054292144, 0.0, 1.2076282160399163, ...",5,LYS
...,...,...,...,...
241,58.983930,"[0.0, 25.36019253683824, 3.622884648119749, 30...",242,GLY
242,193.173391,"[10.935884027146072, 3.622884648119749, 2.4152...",243,GLU
243,75.821786,"[10.935884027146072, 30.190705400997906, 3.622...",244,GLY
244,179.067388,"[2.1871768054292144, 2.4152564320798326, 2.415...",245,GLU
245,219.188882,"[2.1871768054292144, 4.830512864159665, 2.4152...",246,ASN

In [18]:
charge = pd.DataFrame(protein_object.get_charge())
charge

,charge,charge_method,residue_number,residue_name
0,"[-0.12303608460739965, 0.17017601567027532, 0....",gasteiger,1,MET
1,"[-0.19389656694946028, 0.20280639926109276, 0....",gasteiger,2,THR
2,"[-0.1962389594615764, 0.17364340940893375, 0.2...",gasteiger,3,MET
3,"[-0.1957447174724704, 0.18400010768477254, 0.2...",gasteiger,4,ASP
4,"[-0.1963295967163622, 0.1727707663883299, 0.26...",gasteiger,5,LYS
...,...,...,...,...
241,"[-0.1940014083699802, 0.2013937918889632, 0.26...",gasteiger,242,GLY
242,"[-0.19626582326388756, 0.17333291745025875, 0....",gasteiger,243,GLU
243,"[-0.19400128133894276, 0.20139379244984756, 0....",gasteiger,244,GLY
244,"[-0.1962658227370993, 0.1733330417739578, 0.26...",gasteiger,245,GLU
245,"[-0.1936284511054185, 0.20694441437539093, 0.3...",gasteiger,246,ASN

In [19]:
full_psp_df[['ACC_ID','RES_NUM']]

        ACC_ID  RES_NUM
0       P31946        2
1       P31946        6
2       P31946       21
3       P31946       32
4       P31946       39
...        ...      ...
436007  Q96NZ9      113
436008  P13727       23
436009  P13727       24
436010  P13727       25
436011  Q9H741      185

[436012 rows x 2 columns]