In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns

In [2]:
interfaces_data = pd.read_csv("/people/imal967/git_repos/pheno_analysis/results/merged_interfaces_FINAL2.csv")
interfaces_data

,Unnamed: 0.1,Unnamed: 0,GENE,PROTEIN,ACC_ID,HU_CHR_LOC,MOD_RSD,SITE_GRP_ID,ORGANISM,MW_kD,...,uniprotID,AA,res_number,pK,state,position,uniprot_id,closest_interface,inside_interface,distance_from_interface
0,0,0,YWHAB,14-3-3 beta,P31946,20q13.12,T2-p,15718712,human,28.08,...,P31946,THR,2.0,NaN,undefined,2.0,P31946,P51114,0,18.400596
1,1,1,YWHAB,14-3-3 beta,P31946,20q13.12,S6-p,15718709,human,28.08,...,P31946,SER,6.0,NaN,undefined,6.0,P31946,",P31946",1,0.000000
2,2,2,YWHAB,14-3-3 beta,P31946,20q13.12,Y21-p,3426383,human,28.08,...,P31946,TYR,21.0,11.100927,protonated,21.0,P31946,",P31040,P30086,P12931,P67775,P68402,O75317,Q3L...",1,0.000000
3,3,3,YWHAB,14-3-3 beta,P31946,20q13.12,T32-p,23077803,human,28.08,...,P31946,THR,32.0,NaN,undefined,32.0,P31946,O75317,0,15.828202
4,4,4,YWHAB,14-3-3 beta,P31946,20q13.12,S39-p,27442700,human,28.08,...,P31946,SER,39.0,NaN,undefined,39.0,P31946,Q9UHV9,0,16.123331
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
436007,435125,435258,PRAP1,PRAP1,Q96NZ9,10q26.3,Y113-ga,27914389,human,17.21,...,Q96NZ9,TYR,113.0,9.888425,protonated,113.0,Q96NZ9,Q96EQ0,0,19.475904
436008,435127,435260,PRG2,PRG2,P13727,11q12.1,T23-ga,27914778,human,25.21,...,P13727,THR,23.0,NaN,undefined,23.0,P13727,Q86Z23,0,25.513050
436009,435128,435261,PRG2,PRG2,P13727,11q12.1,S24-ga,27914781,human,25.21,...,P13727,SER,24.0,NaN,undefined,24.0,P13727,Q86Z23,0,27.206643
436010,435129,435262,PRG2,PRG2,P13727,11q12.1,T25-ga,27914784,human,25.21,...,P13727,THR,25.0,NaN,undefined,25.0,P13727,Q86Z23,0,29.210871
436011,435308,435441,SPRING1,SPRING1,Q9H741,12q24.22,T185-ga,27916207,human,23.59,...,Q9H741,THR,185.0,NaN,undefined,185.0,Q9H741,",Q14703,P29558",1,0.000000

In [4]:
pockets_data = pd.read_csv("/people/imal967/git_repos/pheno_analysis/results/merged_pockets_FINAL.csv")
pockets_data

,Unnamed: 0.1,Unnamed: 0,GENE,PROTEIN,ACC_ID,HU_CHR_LOC,MOD_RSD,SITE_GRP_ID,ORGANISM,MW_kD,...,uniprotID,AA,res_number,pK,state,position,uniprot_id,closest_pocket,inside_pocket,distance_from_pocket
0,0,0,YWHAB,14-3-3 beta,P31946,20q13.12,T2-p,15718712,human,28.08,...,P31946,THR,2.0,NaN,undefined,2.0,P31946,2,0,22.103256
1,1,1,YWHAB,14-3-3 beta,P31946,20q13.12,S6-p,15718709,human,28.08,...,P31946,SER,6.0,NaN,undefined,6.0,P31946,10,0,18.407673
2,2,2,YWHAB,14-3-3 beta,P31946,20q13.12,Y21-p,3426383,human,28.08,...,P31946,TYR,21.0,11.100927,protonated,21.0,P31946,",2,15",1,0.000000
3,3,3,YWHAB,14-3-3 beta,P31946,20q13.12,T32-p,23077803,human,28.08,...,P31946,THR,32.0,NaN,undefined,32.0,P31946,10,0,12.921682
4,4,4,YWHAB,14-3-3 beta,P31946,20q13.12,S39-p,27442700,human,28.08,...,P31946,SER,39.0,NaN,undefined,39.0,P31946,",10",1,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
436007,435125,435258,PRAP1,PRAP1,Q96NZ9,10q26.3,Y113-ga,27914389,human,17.21,...,Q96NZ9,TYR,113.0,9.888425,protonated,113.0,Q96NZ9,1,0,22.441628
436008,435127,435260,PRG2,PRG2,P13727,11q12.1,T23-ga,27914778,human,25.21,...,P13727,THR,23.0,NaN,undefined,23.0,P13727,4,0,26.709694
436009,435128,435261,PRG2,PRG2,P13727,11q12.1,S24-ga,27914781,human,25.21,...,P13727,SER,24.0,NaN,undefined,24.0,P13727,4,0,29.435677
436010,435129,435262,PRG2,PRG2,P13727,11q12.1,T25-ga,27914784,human,25.21,...,P13727,THR,25.0,NaN,undefined,25.0,P13727,4,0,30.474608
436011,435308,435441,SPRING1,SPRING1,Q9H741,12q24.22,T185-ga,27916207,human,23.59,...,Q9H741,THR,185.0,NaN,undefined,185.0,Q9H741,",8",1,0.000000

In [6]:
# isolating to only inside pocket or interface
inside_pocket_df = pockets_data[pockets_data['inside_pocket'] == 1]
inside_interface_df = interfaces_data[interfaces_data['inside_interface'] == 1]
print(pockets_data.shape)
print(inside_pocket_df.shape)
print(interfaces_data.shape)
print(inside_interface_df.shape)

(436012, 29)
(162921, 29)
(436012, 29)
(45737, 29)

In [48]:
# condensing df's to 1 row per protein and add up the inside pocket
agg_method = {
        "ACC_ID": lambda x: x.iloc[0],
        "GENE": lambda x: x.iloc[0],
        "PROTEIN": lambda x: x.iloc[0],
        "res_number": lambda x: ', '.join(x.astype("string").values),
        "AA": lambda x: ','.join(x.values),
        "closest_pocket": lambda x: ','.join(x.str.slice(1)),
        "inside_pocket": lambda x: x.sum()
    }
inside_pocket_df = inside_pocket_df.groupby(by="ACC_ID", as_index=False).agg(agg_method)
inside_pocket_df

,ACC_ID,GENE,PROTEIN,res_number,AA,closest_pocket,inside_pocket
0,A0A024RBG1,NUDT4B,NUDT4B,"5.0, 128.0, 134.0, 143.0","LYS,LYS,LYS,LYS",",3,7,9,1,9",4
1,A0A075B759,PPIAL4E,PPIAL4E,93.0,THR,,1
2,A0A096LP55,UQCRHL,UQCRHL,"42.0, 42.0","LYS,LYS",",1",2
3,A0A0A6YYL3,POTEB,POTEB,258.0,LYS,"0,12",1
4,A0A0B4J237,TRAV8-2,TRAV8-2,"77.0, 87.0","LYS,LYS",",3",2
...,...,...,...,...,...,...,...
15924,Q9Y6Y0,IVNS1ABP,IVNS1ABP,"28.0, 54.0, 63.0, 71.0, 276.0, 277.0, 284.0, 3...","SER,SER,SER,SER,SER,SER,SER,SER,SER,TYR,THR,TY...","5,7,3,6,3,3,3,2,31,4,20,28,14,1,5,11,15,2,8,9,...",23
15925,Q9Y6Y1,CAMTA1,CAMTA1,"117.0, 152.0, 1060.0, 1138.0, 1142.0","TYR,TYR,SER,SER,SER","7,2,9,37,1,19,32,6,33,5,6,17",5
15926,Q9Y6Y8,SEC23IP,SEC23IP,"602.0, 648.0, 712.0, 862.0, 864.0, 893.0, 926....","SER,THR,SER,SER,SER,THR,SER,SER,TYR,LYS,LYS,LY...","3,13,43,58,47,3,27,21,27,3,27,8,20,52,5,19,10,...",26
15927,Q9Y6Y9,LY96,LY96,"22.0, 131.0","TYR,TYR",",5",2
15928,Q9Y6Z7,COLEC10,COLEC10,"155.0, 201.0","THR,LYS",",6,3",2

In [49]:
agg_method = {
        "ACC_ID": lambda x: x.iloc[0],
        "GENE": lambda x: x.iloc[0],
        "PROTEIN": lambda x: x.iloc[0],
        "res_number": lambda x: ', '.join(x.astype("string").values),
        "AA": lambda x: ','.join(x.values),
        "closest_interface": lambda x: ','.join(x.str.slice(1)),
        "inside_interface": lambda x: x.sum()
    }
inside_interface_df = inside_interface_df.groupby(by="ACC_ID", as_index=False).agg(agg_method)
inside_interface_df

,ACC_ID,GENE,PROTEIN,res_number,AA,closest_interface,inside_interface
0,A0A075B759,PPIAL4E,PPIAL4E,"119.0, 125.0, 125.0","THR,LYS,LYS","P0DN37,P0DN37,P0DN37",3
1,A0A0B4J2A2,PPIAL4C,PPIAL4C,"125.0, 125.0","LYS,LYS","P0DN37,P0DN37",2
2,A0AV96,RBM47,RBM47,"283.0, 77.0","TYR,LYS","Q9NYY8,O14734,P62979,Q9UQM7",2
3,A0AVF1,IFT56,IFT56,"174.0, 36.0, 175.0, 423.0","TYR,LYS,LYS,LYS","Q9NQC8,Q9NQC8,Q9BW83,Q86VQ0",4
4,A0AVT1,UBA6,UBE1L2,"994.0, 1003.0, 238.0, 597.0, 628.0, 729.0, 739...","TYR,LYS,LYS,LYS,LYS,LYS,LYS,LYS,LYS","Q16763,P62253,O43164,Q9BV68,Q9UHC7,Q9BYM8,Q158...",9
...,...,...,...,...,...,...,...
8865,Q9Y6X5,ENPP4,ENPP4,70.0,THR,Q9BXS4,1
8866,Q9Y6X8,ZHX2,ZHX2,654.0,THR,Q9H8Y1,1
8867,Q9Y6X9,MORC2,MORC2,"8.0, 100.0, 434.0, 974.0","SER,TYR,LYS,LYS","Q86VD1,Q86VD1,Q86VD1,Q9H788,Q9H788",4
8868,Q9Y6Y9,LY96,LY96,"22.0, 131.0","TYR,TYR","P42773,Q14696",2
8869,Q9Y6Z7,COLEC10,COLEC10,"141.0, 66.0, 100.0, 103.0","SER,LYS,LYS,LYS","Q9BWP8,Q9BWP8,P11226,P11226,P11226",4